Use class for storing commands descriptions
ksdfg/neko-chan-telebot pull request #66
Opened 2022-05-13 19:19 UTC by ksdfg

Class objects can now be reused for both command previews as well as help texts, centralising the process.

2022-05-13 19:20 UTC, ksdfg commented
@ksdfg #all

2022-05-14 16:28 UTC, akhilnarang requested changes

2022-05-14 16:28 UTC, akhilnarang commented on telebot/utils.py
> +    command: str
You can drop these 5 declarations

2022-05-15 16:34 UTC, ksdfg commented on telebot/utils.py
> +    command: str
ah gg, golang habits

2022-05-15 16:43 UTC, merged

2022-05-15 18:43 UTC, akhilnarang commented on telebot/utils.py
> +    command: str
LMAO